### ISSUE TITLE
Scrolls of Blinding Light missing from prices.lua

### ISSUE THREAD

**Issue by cstegmann** [Road-block/BastionEPGP#2]
The Paladin class trinket 'Scrolls of Blinding Light' (Item Number: 19343) is missing from the prices.lua file.

It drops from Firemaw in BWL.

**Comment by Road-block** [comment]
Thanks I'll add it in the next minor update.  

_Just on an unrelated note since I noticed you forked to make some adjustments for your guild.

The price system is setup so that you can register your own without the need to edit values in the built-in price list or worrying about an update overwriting them.

The example plugins in the AddOns subfolder show alternative dynamic pricing implementations but it could also be a static price list with your own name registered as an option._
